import "./mentionslegales.css";

export default function Mentions(): JSX.Element {
    return (
        <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dignissim sollicitudin sapien. Nam sed egestas ex. Ut dictum nibh non magna cursus aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur id nibh dictum, tincidunt velit ac, blandit neque. In hac habitasse platea dictumst. Mauris hendrerit lobortis metus in varius. Praesent et pretium elit. Etiam quis aliquam risus. Quisque vel varius dolor.

            Phasellus at nisi sed felis congue fringilla. Nam eu sem justo. Donec convallis sollicitudin velit varius tincidunt. In nunc leo, aliquam in cursus et, bibendum vel odio. Pellentesque dignissim, nisl ac aliquet ullamcorper, risus purus efficitur est, sed convallis eros lorem sed lacus. Duis dolor libero, elementum nec orci eget, facilisis porttitor velit. Aliquam rhoncus mollis blandit. Nam placerat maximus ex, at fermentum lacus placerat vel.

            Nullam facilisis turpis sed diam aliquam, et molestie urna congue. Phasellus erat lectus, semper at neque non, suscipit volutpat erat. Vivamus nec finibus magna. Suspendisse et lectus vehicula, maximus diam dictum, luctus mi. Nam tempus massa nec volutpat convallis. Etiam sit amet lorem sit amet arcu laoreet imperdiet facilisis sed augue. Etiam pharetra sodales libero sed viverra. Integer at ex cursus, faucibus massa vel, ullamcorper ex. Integer elementum sagittis diam, sit amet aliquet urna elementum egestas. Maecenas auctor purus eget eleifend fermentum. Phasellus odio nunc, euismod eget tortor interdum, consequat faucibus sem. Aliquam commodo velit at nisl scelerisque mattis. Cras hendrerit tellus pulvinar, facilisis orci eget, consequat velit. Sed pellentesque turpis ut ipsum interdum, in mattis massa finibus. Cras sed imperdiet sem. Sed bibendum, nisl id aliquam facilisis, est nunc ullamcorper ipsum, sit amet tristique tellus lorem ac diam.

            Maecenas massa nunc, aliquam eget ipsum tempor, hendrerit interdum ante. Fusce venenatis rutrum rutrum. Vestibulum tristique finibus ante mollis fermentum. Donec augue risus, scelerisque suscipit sollicitudin et, vehicula in erat. Sed lacinia ultrices urna vel posuere. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras molestie justo eleifend nulla rutrum, eget ornare turpis mattis. Sed blandit arcu vitae dui porta, sit amet gravida sem semper. Nulla imperdiet, metus pulvinar iaculis tempus, sem arcu faucibus ex, eu hendrerit ante est quis odio. Curabitur felis ante, tincidunt a libero et, tempus convallis nisl. Aliquam erat volutpat.

            Donec at ante auctor, ultrices sem eget, maximus ipsum. Ut tincidunt posuere libero, eu lobortis tellus lobortis nec. Etiam quis enim ultricies, viverra libero vel, maximus est. Suspendisse porta nisi a lacus mattis, eget tincidunt est interdum. Aliquam venenatis mi augue, ut posuere lectus sodales id. Donec at mauris id risus accumsan rutrum. Duis ultrices blandit arcu vitae condimentum. Vivamus nec tincidunt sapien. Vivamus a urna non justo accumsan accumsan et at tellus. Phasellus ut sollicitudin lectus. Praesent suscipit quis ipsum vel sollicitudin. Maecenas in eros odio. Donec quis lectus sagittis magna cursus eleifend eget tincidunt nunc. Nunc consequat, mi ut finibus vehicula, enim leo dignissim erat, vitae ornare ante urna id risus.
        </div>
    )
}